# Configuracion de la Base de Datos para DESARROLLO
spring.datasource.url=jdbc:mysql://localhost:3306/deporuis?useSSL=false&serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=none

# Clave secreta segura para desarrollo
jwt.secret=clave-super-secreta-deporuis-1234567890

# 24 horas en milisegundos
jwt.expiration.ms=86400000

# application.properties
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
logging.level.org.springframework.web=DEBUG

# En application.properties o application.yml
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

